#ifndef EXTRACTION_LEVEL1_GLOBAL_H
#define EXTRACTION_LEVEL1_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EXTRACTION_LEVEL1_LIBRARY)
#  define EXTRACTION_LEVEL1_EXPORT Q_DECL_EXPORT
#else
#  define EXTRACTION_LEVEL1_EXPORT Q_DECL_IMPORT
#endif

#endif // EXTRACTION_LEVEL1_GLOBAL_H
